### ISSUE TITLE
Change Column number with different screen sizes.

### ISSUE THREAD

**Issue by DeysonOrtiz** [dmbdesignpdx/flexr#1]
Hello and good day. Thank you for your great work!  It works great.

I had one question.  Is there a way to change the number of columns based on screen size?  

Thank you and have a great day!

**Comment by dmbdesignpdx** [comment]
Hello and thank you!

The only option that would "change" the number of columns would be to use the expanding class (.exp) on the column's parent row. That effectively turns a col-1 to col-2, col-2 to col-4, col-3 to col-6, and col-4 & col-6 to col-12, so that they can stack evenly.

You can check out that behavior here: http://flexrgrid.com/flexr-grid.html

**Comment by DeysonOrtiz** [comment]
Thank you very much! You rock!  Also, your website portfolio is amazing!  Keep up the great work and thank you for sharing Flexr.  So far it is the only one I could find that works perfectly with Mediaelements.js video.  Perfect work!

**Comment by dmbdesignpdx** [comment]
Thank you, I appreciate it!

**Comment by DeysonOrtiz** [comment]
You are welcome.  I have shared your link with MediaElements.js and they plan to add your link to the documentation for reference. :)  Thank you again and have a great day!

Here is the link:
https://github.com/johndyer/mediaelement/issues/2093#issuecomment-280965181
